name: Release to Clojars


on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  clojars:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install dependencies
        run: clojure -P -T:build

      - name: Publish to Clojars
        run: clojure -T:build deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
